version: '3.1'

services:

  nginx:
    container_name: symfony2-nginx
    image: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./:/app
      - ./docker/etc/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    restart: always

  php:
    container_name: symfony2-php
    build: ./docker/php
    expose:
      - 9001
    volumes:
      - ./:/app
      - ./docker/etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /app
    environment:
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
      COMPOSER_ALLOW_SUPERUSER: 1

  postgres:
    container_name: symfony2-postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/.data/:/var/lib/postgresql
